services:
  postgres:
    image: postgres:15
    container_name: projecty-postgres
    environment:
      POSTGRES_USER: projecty
      POSTGRES_PASSWORD: projecty
      POSTGRES_DB: projecty_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U projecty -d projecty_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: projecty-backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://projecty:projecty@postgres:5432/projecty_db
      JWT_SECRET: supersecret
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: projecty-frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
